# Generated by Django 3.0.5 on 2020-04-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_trailor',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
